---
apt_keys:
  - url: https://dl.google.com/linux/linux_signing_key.pub
    keyname: /etc/apt/keyrings/googlechrom-keyring.asc
  - url: https://packages.microsoft.com/keys/microsoft.asc
    keyname: /etc/apt/keyrings/packages.microsoft.asc
  - url: https://download.docker.com/linux/ubuntu/gpg
    keyname: /etc/apt/keyrings/docker.asc
  - url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x08633B4AAAEB49FC
    keyname: /etc/apt/keyrings/discord.asc
  - url: https://dl.winehq.org/wine-builds/Release.key
    keyname: /usr/share/keyrings/winehq-archive.asc
  - url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    keyname: /etc/apt/keyrings/githubcli-archive-keyring.gpg
  - url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    keyname: /usr/share/keyrings/oracle-vbox.asc
apt_repositories:
  - deb [arch=amd64 signed-by=/etc/apt/keyrings/googlechrom-keyring.asc] http://dl.google.com/linux/chrome/deb/ stable main
  - ppa:kicad/kicad-9.0-releases
  - deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  - ppa:obsproject/obs-studio
  - deb [arch=amd64 signed-by=/etc/apt/keyrings/discord.asc] https://ppa.javinator9889.com all main
  - ppa:ansible/ansible
  - ppa:apt-fast/stable
  - ppa:zhangsongcui3371/fastfetch
  - ppa:lakinduakash/lwh
  - deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
  - deb [signed-by=/usr/share/keyrings/oracle-vbox.asc] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }}  contrib
apt_packages:
  - dirmngr
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - ffmpeg
  - apt-fast
  - google-chrome-stable
  - rpi-imager
  - ibus-mozc
  - mozc-utils-gui
  - curl
  - apt-transport-https
  - git
  - kicad
  - clang
  - clangd
  - clang-format
  - build-essential
  - libreoffice
  - docker-ce
  - docker-ce-cli
  - blender
  - obs-studio
  - network-manager-l2tp
  - network-manager-l2tp-gnome
  - xsel
  - python3-pip
  - exuberant-ctags
  - ripgrep
  - eza
  - make
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
  - lldb
  - libxslt1-dev
  - autoconf
  - bison
  - libyaml-dev
  - libncurses5-dev
  - libgdbm-dev
  - libdb-dev
  - uuid-dev
  - htop
  - net-tools
  - trash-cli
  - nmap
  - openssh-server
  - bacula-console-qt
  - discord
  - blueman
  - apt-fast
  - direnv
  - cargo
  - sshpass
  - docker-compose-plugin
  - tigervnc-viewer
  - zsh
  - libheif-examples
  - fortune-mod
  - software-properties-common
  - ansible
  - v4l-utils
  - cheese
  - micropython
  - cmake
  - ninja-build
  - libfuse2t64
  - aria2
  - tmux
  - tree
  - ncdu
  - avahi-daemon
  - fastfetch
  - hydra
  - gcc-11
  - g++-11
  - gcc-12
  - g++-12
  - gcc-13
  - g++-13
  - clang-14
  - clang-15
  - clang-16
  - clang-17
  - clang-18
  - clang-19
  - arp-scan
  - vim
  - dnsmasq
  - hostapd
  - isc-dhcp-server
  - linux-wifi-hotspot
  - gh
  - openjdk-21-jdk
  - libboost-all-dev
  - mysql-client
  - asunder
  - lame
  - sg3-utils
  - libopencv-dev
  - apache2-utils
  - screen
  - virtualbox-7.1
  - libcgi-pm-perl
  - dos2unix
  - rubberband-cli
  - sox
  - libsox-fmt-mp3
  - neovim
  - opam
  - ocamlbuild
  - python3-tk
  - bat
  - cu
  - postgresql-client-common
  - postgresql-client
  - golang-go
  - portaudio19-dev
  - python3-pyaudio
  - imagemagick
  - libmagickwand-dev
  - kitty
  - parallel
  - libgtkmm-3.0-dev
  - libcurl4-gnutls-dev
  - libsqlite3-dev
  - libssl-dev
  - nlohmann-json3-dev
  - libhandy-1-dev
  - libsecret-1-dev
  - libopus-dev
  - libsodium-dev
  - libspdlog-dev
  - gnuplot
  - flatpak
  - gnome-software-plugin-flatpak
  - hwinfo
  - libimobiledevice-utils
  - libimobiledevice6
  - ifuse
  - libapr1
  - libaprutil1
  - libasound2t64
  - libasound2-data
  - libglib2.0-0
  - libxcb-cursor0
  - fakeroot
  - xorriso
  - ocl-icd-libopencl1
  - mesa-opencl-icd
  - ocl-icd-opencl-dev
  - wpasupplicant
  - dnsmasq
  - iptables
  - ipheth-utils
  - libimobiledevice-utils
  - usbmuxd
  - libimobiledevice6
  - isc-dhcp-client
  - linux-image-generic
  - linux-headers-generic

