---
asdf_plugins_without_dest:
  -
    name: python
    version: 3.12.6
  -
    name: ruby
    version: 3.3.6
  -
    name: lazygit
    version: latest
  -
    name: nodejs
    version: latest
asdf_plugins_with_dest:
  -
    name: lazydocker
    url: https://github.com/comdotlinux/asdf-lazydocker.git
    version: latest
npm_packages:
  - atcoder-cli
  - "@google/gemini-cli"
pip_packages:
  - jedi
  - yapf
  - uv
  - "git+https://github.com/rotarymars/oj.git"
