$ANSIBLE_VAULT;1.1;AES256
36646665623639336535316563393234353161333731313937376564313733353331383936373337
6333376166643032336362363762306663363932343338620a646661363764653365346639636337
62373138346334663166306233623366656134623034316132626438396462356137363261396637
3061626134353435650a613066653330316131313032333235363039363835333064346532316233
39656631373337613365646237343164376266323734343962646161636361313935326566666265
63343961336433383862663631376437316137326430316566613266326566373962626435616563
34376533613662656632316331396337306434343130656634633534633233363166303235393636
32636363616137313830353232636465373534386266383466373034613435333630616235326638
3962
